// Generated protobuf code from intelligence.proto
// This is generated by build.rs using tonic-prost-build

// Wrap the generated code in the expected module structure
pub mod opentier {
    pub mod intelligence {
        #[allow(clippy::enum_variant_names, clippy::all, dead_code)]
        pub mod v1 {
            // Include the generated proto code
            // The file is generated in OUT_DIR during build
            include!(concat!(env!("OUT_DIR"), "/opentier.intelligence.v1.rs"));
        }
    }
}
